### ISSUE TITLE
[Config Request] Disable Furnace option and may more

### ISSUE THREAD

**Issue by xR4YM0ND** [Iunius118/ToLaserBlade-Fabric#2]
Hey there, i wanna disable the lit furnace cause of balancing reason, can you add a config for that pls

**Comment by Iunius118** [comment]
Thanks for the request.

> can you add a config for that pls

Yes, I will add a config file for the ability to use the dispenser and furnace.
It will only update the current development version, 1.18.2.

**Comment by xR4YM0ND** [comment]
<3 thank you for replying and updating the mod , and for making the mod ofcourse

**Comment by xR4YM0ND** [comment]
Do you know that you have 
- disabled the comments on curseforge
- problem page on curseforge
- & a issue page on github

maybe you disable the problem page and link to the github issue page 

maybe ^^ ok cy
