### ISSUE TITLE
[Suggestion] Compatibility with better combat

### ISSUE THREAD

**Issue by Rad586** [Iunius118/ToLaserBlade-Fabric#4]
Mod version: 1.18.2 fabric 0.5.0.0
Would be nice if compatible with better combat.
I remixed a royalty free sound and make it a light saber fast swing sound effect for this mod.
[sounds.zip](https://github.com/Iunius118/ToLaserBlade-Fabric/files/10303259/sounds.zip)
And... where's the client config file? I couldn't find it.

**Comment by Iunius118** [comment]
Sounds when the laser blade is swung can be added with a resource pack.
They are defined in the following file by default:
- [assets/tolaserblade/sounds.json](https://github.com/Iunius118/ToLaserBlade-Fabric/blob/1.18.x/src/main/resources/assets/tolaserblade/sounds.json)

Then place .ogg files as follows and they should play:
- `assets/tolaserblade/sounds/item/laser_blade/swing.ogg` (for Laser Blade)
- `assets/tolaserblade/sounds/item/laser_blade_fp/swing.ogg` (for fireproof Laser Blade)

**Comment by Iunius118** [comment]
If you want to use your sound files, make a json file:
```json
{
  "item.laser_blade.swing": {
    "replace": true,
    "sounds": [
      "tolaserblade:item/laser_blade/swing1",
      "tolaserblade:item/laser_blade/swing2"
    ]
  },
  "item.laser_blade_fp.swing": {
    "replace": true,
    "sounds": [
      "tolaserblade:item/laser_blade/swing1",
      "tolaserblade:item/laser_blade/swing2"
    ]
  }
}
```
And save it to `assets/tolaserblade/sounds.json` in your resource pack.
Then place your sound files in `assets/tolaserblade/sounds/item/laser_blade/` in the resource pack.

**Comment by Rad586** [comment]
> 
Thanks for replying! 
Is it possible to merge these sound effects into a new update of your mod?

The laser blade is not rendered with shaders on, I tried to find the client config file(also tried /config showfile in-game) of this mod but failed, here's a screenshot: https://i.postimg.cc/4xMFW94W/1.png

**Comment by Iunius118** [comment]
Thank you for your suggestion, but I have no plans to add any sound files to the mod, because I want to avoid the mod having excessive references to specific fictions.

The client config is also in tolaserblade.toml. If `useOriginalShaderProgram` in the config is set to `false`, some shaders can render the laser blade. However, not all shaders can render the laser blade, as each shader has a different process.

**Comment by Rad586** [comment]
> Thank you for your suggestion, but I have no plans to add any sound files to the mod, because I want to avoid the mod having excessive references to specific fictions.
> 
> The client config is also in tolaserblade.toml. If `useOriginalShaderProgram` in the config is set to `false`, some shaders can render the laser blade. However, not all shaders can render the laser blade, as each shader has a different process.

Got it, thanks! 

Screenshot:https://i.postimg.cc/0y2pNzws/1.png Can't find _useOriginalShaderProgram_ in config file, I tried to add a line but it disappers(while keeping other settings) after restarting the game. Is this a bug?

**Comment by Iunius118** [comment]
Sorry, I forgot that the configuration item was added in 1.19.

I made v1.18.2-0.6.0.4, please try it.
https://github.com/Iunius118/ToLaserBlade-Fabric/releases/tag/v1.18.2-0.6.0.4

**Comment by Rad586** [comment]
> Sorry, I forgot that the configuration item was added in 1.19.
> 
> I made v1.18.2-0.6.0.4, please try it. https://github.com/Iunius118/ToLaserBlade-Fabric/releases/tag/v1.18.2-0.6.0.4

It's now working, thanks!
