### ISSUE TITLE
Incompatibility with shaders

### ISSUE THREAD

**Issue by GDHJDSYDH** [Iunius118/ToLaserBlade-Fabric#6]
- Minecraft version: 1.20.1
- Fabric Loader version: 0.14.22
- Fabric API version: 0.89.0
- ToLaserBlade version: 2.0.0

The blade body of the Laser Blade did not render successfully with the shader turned on.

![2023-09-27_22 28 04](https://github.com/Iunius118/ToLaserBlade-Fabric/assets/32081161/51e18ebe-3541-4ece-b25e-57b31d3f2a1a)
![2023-09-27_22 28 19](https://github.com/Iunius118/ToLaserBlade-Fabric/assets/32081161/56cdc856-aac0-4248-a21e-b0a2b4c176bc)

**Comment by Iunius118** [comment]
Try setting useOriginalShaderProgram in config/tolaserblade.toml to `false` and restart the game. This setting allows the shader mod to render laser blades.
However, not all shader packs can render the laser blade well, as each shader pack has a different process.

**Comment by GDHJDSYDH** [comment]
Fixed
